export default {
	"day_1": "Monday",
	"day_2": "Tuesday",
	"day_3": "Wednesday",
	"day_4": "Thursday",
	"day_5": "Friday",
	"day_6": "Saturday",
	"day_7": "Sunday",

	"month_0": "January",
	"month_1": "February",
	"month_2": "March",
	"month_3": "April",
	"month_4": "May",
	"month_5": "June",
	"month_6": "July",
	"month_7": "August",
	"month_8": "September",
	"month_9": "October",
	"month_10": "November",
	"month_11": "December",

	"am": "am",
	"pm": "pm",

	"just_now": "just now",
	"ago": "ago",
	"since": "since",

	"century": "century",
	"centurys": "centuries",
	"decade": "decade",
	"decades": "decades",
	"year": "year",
	"years": "years",
	"month": "month",
	"months": "months",
	"week": "week",
	"weeks": "weeks",
	"day": "day",
	"days": "days",
	"hour": "hour",
	"hours": "hours",
	"minute": "minute",
	"minutes": "minutes",
	"second": "second",
	"seconds": "seconds"
};
